export * from './authenticate.service';
import { AuthenticateService } from './authenticate.service';
export * from './batchExport.service';
import { BatchExportService } from './batchExport.service';
export * from './bidItem.service';
import { BidItemService } from './bidItem.service';
export * from './comment.service';
import { CommentService } from './comment.service';
export * from './contract.service';
import { ContractService } from './contract.service';
export * from './customer.service';
import { CustomerService } from './customer.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './documentApproval.service';
import { DocumentApprovalService } from './documentApproval.service';
export * from './documentSendTo.service';
import { DocumentSendToService } from './documentSendTo.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './documentsByObservation.service';
import { DocumentsByObservationService } from './documentsByObservation.service';
export * from './electronicSignature.service';
import { ElectronicSignatureService } from './electronicSignature.service';
export * from './equipment.service';
import { EquipmentService } from './equipment.service';
export * from './lineItem.service';
import { LineItemService } from './lineItem.service';
export * from './module.service';
import { ModuleService } from './module.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './observation.service';
import { ObservationService } from './observation.service';
export * from './observationCloneTemplates.service';
import { ObservationCloneTemplatesService } from './observationCloneTemplates.service';
export * from './observationSearchs.service';
import { ObservationSearchsService } from './observationSearchs.service';
export * from './observationSendTo.service';
import { ObservationSendToService } from './observationSendTo.service';
export * from './observationsBatchTag.service';
import { ObservationsBatchTagService } from './observationsBatchTag.service';
export * from './observationsByDocument.service';
import { ObservationsByDocumentService } from './observationsByDocument.service';
export * from './observationsByUpdateDate.service';
import { ObservationsByUpdateDateService } from './observationsByUpdateDate.service';
export * from './observationsFilter.service';
import { ObservationsFilterService } from './observationsFilter.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './payItem.service';
import { PayItemService } from './payItem.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './report.service';
import { ReportService } from './report.service';
export * from './reportNamedInstance.service';
import { ReportNamedInstanceService } from './reportNamedInstance.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthenticateService, BatchExportService, BidItemService, CommentService, ContractService, CustomerService, DocumentService, DocumentApprovalService, DocumentSendToService, DocumentsService, DocumentsByObservationService, ElectronicSignatureService, EquipmentService, LineItemService, ModuleService, NotificationService, ObservationService, ObservationCloneTemplatesService, ObservationSearchsService, ObservationSendToService, ObservationsBatchTagService, ObservationsByDocumentService, ObservationsByUpdateDateService, ObservationsFilterService, OrganizationService, PayItemService, ProjectService, ReportService, ReportNamedInstanceService, UserService];
