export * from './artifact.service';
import { ArtifactService } from './artifact.service';
export * from './authenticate.service';
import { AuthenticateService } from './authenticate.service';
export * from './batchExport.service';
import { BatchExportService } from './batchExport.service';
export * from './bidItem.service';
import { BidItemService } from './bidItem.service';
export * from './comment.service';
import { CommentService } from './comment.service';
export * from './contract.service';
import { ContractService } from './contract.service';
export * from './customer.service';
import { CustomerService } from './customer.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './documentApproval.service';
import { DocumentApprovalService } from './documentApproval.service';
export * from './documentPolyJoin.service';
import { DocumentPolyJoinService } from './documentPolyJoin.service';
export * from './documentSendTo.service';
import { DocumentSendToService } from './documentSendTo.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './documentsByObservation.service';
import { DocumentsByObservationService } from './documentsByObservation.service';
export * from './electronicSignature.service';
import { ElectronicSignatureService } from './electronicSignature.service';
export * from './equipment.service';
import { EquipmentService } from './equipment.service';
export * from './lab.service';
import { LabService } from './lab.service';
export * from './labMaterialAssignment.service';
import { LabMaterialAssignmentService } from './labMaterialAssignment.service';
export * from './labTestApproval.service';
import { LabTestApprovalService } from './labTestApproval.service';
export * from './labTestDefault.service';
import { LabTestDefaultService } from './labTestDefault.service';
export * from './lineItem.service';
import { LineItemService } from './lineItem.service';
export * from './material.service';
import { MaterialService } from './material.service';
export * from './materialLineItemJoin.service';
import { MaterialLineItemJoinService } from './materialLineItemJoin.service';
export * from './materialPayItemJoin.service';
import { MaterialPayItemJoinService } from './materialPayItemJoin.service';
export * from './materialRecordOfMaterialEntryJoin.service';
import { MaterialRecordOfMaterialEntryJoinService } from './materialRecordOfMaterialEntryJoin.service';
export * from './mixSpecification.service';
import { MixSpecificationService } from './mixSpecification.service';
export * from './mixSpecificationMaterialJoin.service';
import { MixSpecificationMaterialJoinService } from './mixSpecificationMaterialJoin.service';
export * from './module.service';
import { ModuleService } from './module.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './observation.service';
import { ObservationService } from './observation.service';
export * from './observationApproval.service';
import { ObservationApprovalService } from './observationApproval.service';
export * from './observationCloneTemplates.service';
import { ObservationCloneTemplatesService } from './observationCloneTemplates.service';
export * from './observationSearchs.service';
import { ObservationSearchsService } from './observationSearchs.service';
export * from './observationSendTo.service';
import { ObservationSendToService } from './observationSendTo.service';
export * from './observationsBatchTag.service';
import { ObservationsBatchTagService } from './observationsBatchTag.service';
export * from './observationsByDocument.service';
import { ObservationsByDocumentService } from './observationsByDocument.service';
export * from './observationsByUpdateDate.service';
import { ObservationsByUpdateDateService } from './observationsByUpdateDate.service';
export * from './observationsFilter.service';
import { ObservationsFilterService } from './observationsFilter.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './organizationMaterialJoin.service';
import { OrganizationMaterialJoinService } from './organizationMaterialJoin.service';
export * from './payItem.service';
import { PayItemService } from './payItem.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './productionPlant.service';
import { ProductionPlantService } from './productionPlant.service';
export * from './productionPlantMaterialApproval.service';
import { ProductionPlantMaterialApprovalService } from './productionPlantMaterialApproval.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './recordOfMaterial.service';
import { RecordOfMaterialService } from './recordOfMaterial.service';
export * from './recordOfMaterialEntry.service';
import { RecordOfMaterialEntryService } from './recordOfMaterialEntry.service';
export * from './recordOfMaterialEntryArchive.service';
import { RecordOfMaterialEntryArchiveService } from './recordOfMaterialEntryArchive.service';
export * from './report.service';
import { ReportService } from './report.service';
export * from './reportNamedInstance.service';
import { ReportNamedInstanceService } from './reportNamedInstance.service';
export * from './sample.service';
import { SampleService } from './sample.service';
export * from './sampleLabJoin.service';
import { SampleLabJoinService } from './sampleLabJoin.service';
export * from './sampleLineItemJoin.service';
import { SampleLineItemJoinService } from './sampleLineItemJoin.service';
export * from './sampleLog.service';
import { SampleLogService } from './sampleLog.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './testData.service';
import { TestDataService } from './testData.service';
export * from './testInstance.service';
import { TestInstanceService } from './testInstance.service';
export * from './testInstanceData.service';
import { TestInstanceDataService } from './testInstanceData.service';
export * from './testInstanceDataArchive.service';
import { TestInstanceDataArchiveService } from './testInstanceDataArchive.service';
export * from './testInstanceLabJoin.service';
import { TestInstanceLabJoinService } from './testInstanceLabJoin.service';
export * from './testInstanceSampleJoin.service';
import { TestInstanceSampleJoinService } from './testInstanceSampleJoin.service';
export * from './testLabJoin.service';
import { TestLabJoinService } from './testLabJoin.service';
export * from './testPlan.service';
import { TestPlanService } from './testPlan.service';
export * from './testRecordOfMaterialEntryJoin.service';
import { TestRecordOfMaterialEntryJoinService } from './testRecordOfMaterialEntryJoin.service';
export * from './testSpecification.service';
import { TestSpecificationService } from './testSpecification.service';
export * from './testSpecificationMaterialTestJoin.service';
import { TestSpecificationMaterialTestJoinService } from './testSpecificationMaterialTestJoin.service';
export * from './testSpecificationRequirement.service';
import { TestSpecificationRequirementService } from './testSpecificationRequirement.service';
export * from './testSpecificationSet.service';
import { TestSpecificationSetService } from './testSpecificationSet.service';
export * from './testSpecificationSetTestJoin.service';
import { TestSpecificationSetTestJoinService } from './testSpecificationSetTestJoin.service';
export * from './testStep.service';
import { TestStepService } from './testStep.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ArtifactService, AuthenticateService, BatchExportService, BidItemService, CommentService, ContractService, CustomerService, DocumentService, DocumentApprovalService, DocumentPolyJoinService, DocumentSendToService, DocumentsService, DocumentsByObservationService, ElectronicSignatureService, EquipmentService, LabService, LabMaterialAssignmentService, LabTestApprovalService, LabTestDefaultService, LineItemService, MaterialService, MaterialLineItemJoinService, MaterialPayItemJoinService, MaterialRecordOfMaterialEntryJoinService, MixSpecificationService, MixSpecificationMaterialJoinService, ModuleService, NotificationService, ObservationService, ObservationApprovalService, ObservationCloneTemplatesService, ObservationSearchsService, ObservationSendToService, ObservationsBatchTagService, ObservationsByDocumentService, ObservationsByUpdateDateService, ObservationsFilterService, OrganizationService, OrganizationMaterialJoinService, PayItemService, ProductService, ProductionPlantService, ProductionPlantMaterialApprovalService, ProjectService, RecordOfMaterialService, RecordOfMaterialEntryService, RecordOfMaterialEntryArchiveService, ReportService, ReportNamedInstanceService, SampleService, SampleLabJoinService, SampleLineItemJoinService, SampleLogService, TestService, TestDataService, TestInstanceService, TestInstanceDataService, TestInstanceDataArchiveService, TestInstanceLabJoinService, TestInstanceSampleJoinService, TestLabJoinService, TestPlanService, TestRecordOfMaterialEntryJoinService, TestSpecificationService, TestSpecificationMaterialTestJoinService, TestSpecificationRequirementService, TestSpecificationSetService, TestSpecificationSetTestJoinService, TestStepService, UserService];
