/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface ISession {
    /**
     * 
     */
    "SessionID": string;
    /**
     * 
     */
    "LoggedIn": boolean;
    /**
     * 
     */
    "UserRole": string;
    /**
     * 
     */
    "UserRoleIndex": number;
    /**
     * 
     */
    "UserID": number;
    /**
     * 
     */
    "CustomerID": number;
    /**
     * 
     */
    "Title": string;
    /**
     * 
     */
    "NameFirst": string;
    /**
     * 
     */
    "NameLast": string;
    /**
     * 
     */
    "Email": string;
    /**
     * 
     */
    "LoginID": string;
    /**
     * 
     */
    "UIHash": string;
    /**
     * 
     */
    "Timezone": string;
    /**
     * 
     */
    "Settings": any;
    /**
     * 
     */
    "DeviceID": string;
    /**
     * 
     */
    "IDDevice": number;
    /**
     * 
     */
    "ServerHostURL": string;
}

