/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface Organization {
    /**
     * 
     */
    "IDOrganization": number;
    /**
     * 
     */
    "GUIDOrganization": string;
    /**
     * 
     */
    "CreateDate": Date;
    /**
     * 
     */
    "CreatingIDUser": number;
    /**
     * 
     */
    "UpdateDate": Date;
    /**
     * 
     */
    "UpdatingIDUser": number;
    /**
     * 
     */
    "Deleted": number;
    /**
     * 
     */
    "DeleteDate": Date;
    /**
     * 
     */
    "DeletingIDUser": number;
    /**
     * 
     */
    "Name": string;
    /**
     * 
     */
    "DisadvantagedBusiness": number;
    /**
     * 
     */
    "Address": string;
    /**
     * 
     */
    "City": string;
    /**
     * 
     */
    "State": string;
    /**
     * 
     */
    "Zip": string;
    /**
     * 
     */
    "Phone": string;
    /**
     * 
     */
    "Approved": number;
    /**
     * 
     */
    "IDCustomer": number;
    /**
     * 
     */
    "ExternalSyncDate": Date;
    /**
     * 
     */
    "Email": string;
    /**
     * 
     */
    "Type": string;
}

