/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface ProjectModel {
    /**
     * DEPRECATED 
     */
    "Tags": Array<string>;
    /**
     * DEPRECATED 
     */
    "BidItems": Array<string>;
    /**
     * DEPRECATED 
     */
    "LineItems": Array<string>;
    /**
     * DEPRECATED 
     */
    "Contractors": Array<string>;
    /**
     * DEPRECATED 
     */
    "TagTypes": Array<string>;
    /**
     * Tag configuration for this project.   Use 1.0/ObservationTagProjectJoins/FilteredTo/FBV~IDProject~EQ~71~FBV~TagType~EQ~Contractor~FSF~Tag~ASC/0/10 to get list of available tags of each type in the project.
     */
    "LabelTypes": any;
    /**
     * 
     */
    "CustomProperties": any;
    /**
     * 
     */
    "IDProject": number;
    /**
     * 
     */
    "GUIDProject": string;
    /**
     * 
     */
    "CreateDate": Date;
    /**
     * 
     */
    "CreatingIDUser": number;
    /**
     * 
     */
    "UpdateDate": Date;
    /**
     * 
     */
    "UpdatingIDUser": number;
    /**
     * 
     */
    "Name": string;
    /**
     * 
     */
    "Description": string;
    /**
     * 
     */
    "Deleted": number;
    /**
     * 
     */
    "DeleteDate": Date;
    /**
     * 
     */
    "DeletingIDUser": number;
    /**
     * 
     */
    "Latitude": string;
    /**
     * 
     */
    "Longitude": string;
    /**
     * 
     */
    "IDCustomer": number;
    /**
     * 
     */
    "IDContract": number;
    /**
     * 
     */
    "ExternalSyncDate": Date;
    /**
     * 
     */
    "Timezone": string;
    /**
     * 
     */
    "Status": string;
}

