/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface ReportNamedInstanceModel {
    /**
     * 
     */
    "Archetype": string;
    /**
     * 
     */
    "Options": any;
    /**
     * 
     */
    "IDReportNamedInstance": number;
    /**
     * 
     */
    "GUIDReportNamedInstance": string;
    /**
     * 
     */
    "CreateDate": Date;
    /**
     * 
     */
    "CreatingIDUser": number;
    /**
     * 
     */
    "UpdateDate": Date;
    /**
     * 
     */
    "UpdatingIDUser": number;
    /**
     * 
     */
    "Deleted": number;
    /**
     * 
     */
    "DeleteDate": Date;
    /**
     * 
     */
    "DeletingIDUser": number;
    /**
     * 
     */
    "Name": string;
    /**
     * 
     */
    "Hash": string;
    /**
     * 
     */
    "OptionsJSON": string;
    /**
     * 
     */
    "IDReportArchetype": number;
    /**
     * 
     */
    "IDCustomer": number;
}

