/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface UserSignupRequest {
    /**
     * 
     */
    "NameFirst": string;
    /**
     * 
     */
    "NameLast": string;
    /**
     * 
     */
    "Email": string;
    /**
     * 
     */
    "Password": string;
    /**
     * 
     */
    "Phone": string;
    /**
     * 
     */
    "CompanyName": string;
    "CompanyDetails": models.UserSignupRequestCompanyDetails;
    /**
     * 
     */
    "Position": string;
}

