export * from './AuthenticateApi';
import { AuthenticateApi } from './AuthenticateApi';
export * from './BatchExportApi';
import { BatchExportApi } from './BatchExportApi';
export * from './BidItemApi';
import { BidItemApi } from './BidItemApi';
export * from './CommentApi';
import { CommentApi } from './CommentApi';
export * from './ContractApi';
import { ContractApi } from './ContractApi';
export * from './CustomerApi';
import { CustomerApi } from './CustomerApi';
export * from './DocumentApi';
import { DocumentApi } from './DocumentApi';
export * from './DocumentApprovalApi';
import { DocumentApprovalApi } from './DocumentApprovalApi';
export * from './DocumentSendToApi';
import { DocumentSendToApi } from './DocumentSendToApi';
export * from './DocumentsApi';
import { DocumentsApi } from './DocumentsApi';
export * from './DocumentsByObservationApi';
import { DocumentsByObservationApi } from './DocumentsByObservationApi';
export * from './ElectronicSignatureApi';
import { ElectronicSignatureApi } from './ElectronicSignatureApi';
export * from './EquipmentApi';
import { EquipmentApi } from './EquipmentApi';
export * from './LineItemApi';
import { LineItemApi } from './LineItemApi';
export * from './ModuleApi';
import { ModuleApi } from './ModuleApi';
export * from './NotificationApi';
import { NotificationApi } from './NotificationApi';
export * from './ObservationApi';
import { ObservationApi } from './ObservationApi';
export * from './ObservationCloneTemplatesApi';
import { ObservationCloneTemplatesApi } from './ObservationCloneTemplatesApi';
export * from './ObservationSearchsApi';
import { ObservationSearchsApi } from './ObservationSearchsApi';
export * from './ObservationSendToApi';
import { ObservationSendToApi } from './ObservationSendToApi';
export * from './ObservationsBatchTagApi';
import { ObservationsBatchTagApi } from './ObservationsBatchTagApi';
export * from './ObservationsByDocumentApi';
import { ObservationsByDocumentApi } from './ObservationsByDocumentApi';
export * from './ObservationsByUpdateDateApi';
import { ObservationsByUpdateDateApi } from './ObservationsByUpdateDateApi';
export * from './ObservationsFilterApi';
import { ObservationsFilterApi } from './ObservationsFilterApi';
export * from './OrganizationApi';
import { OrganizationApi } from './OrganizationApi';
export * from './PayItemApi';
import { PayItemApi } from './PayItemApi';
export * from './ProjectApi';
import { ProjectApi } from './ProjectApi';
export * from './ReportApi';
import { ReportApi } from './ReportApi';
export * from './ReportNamedInstanceApi';
import { ReportNamedInstanceApi } from './ReportNamedInstanceApi';
export * from './UserApi';
import { UserApi } from './UserApi';
export const APIS = [AuthenticateApi, BatchExportApi, BidItemApi, CommentApi, ContractApi, CustomerApi, DocumentApi, DocumentApprovalApi, DocumentSendToApi, DocumentsApi, DocumentsByObservationApi, ElectronicSignatureApi, EquipmentApi, LineItemApi, ModuleApi, NotificationApi, ObservationApi, ObservationCloneTemplatesApi, ObservationSearchsApi, ObservationSendToApi, ObservationsBatchTagApi, ObservationsByDocumentApi, ObservationsByUpdateDateApi, ObservationsFilterApi, OrganizationApi, PayItemApi, ProjectApi, ReportApi, ReportNamedInstanceApi, UserApi];
