export * from './ArtifactApi';
import { ArtifactApi } from './ArtifactApi';
export * from './AuthenticateApi';
import { AuthenticateApi } from './AuthenticateApi';
export * from './BatchExportApi';
import { BatchExportApi } from './BatchExportApi';
export * from './BidItemApi';
import { BidItemApi } from './BidItemApi';
export * from './CommentApi';
import { CommentApi } from './CommentApi';
export * from './ContractApi';
import { ContractApi } from './ContractApi';
export * from './CustomerApi';
import { CustomerApi } from './CustomerApi';
export * from './DocumentApi';
import { DocumentApi } from './DocumentApi';
export * from './DocumentApprovalApi';
import { DocumentApprovalApi } from './DocumentApprovalApi';
export * from './DocumentSendToApi';
import { DocumentSendToApi } from './DocumentSendToApi';
export * from './DocumentsApi';
import { DocumentsApi } from './DocumentsApi';
export * from './DocumentsByObservationApi';
import { DocumentsByObservationApi } from './DocumentsByObservationApi';
export * from './ElectronicSignatureApi';
import { ElectronicSignatureApi } from './ElectronicSignatureApi';
export * from './EquipmentApi';
import { EquipmentApi } from './EquipmentApi';
export * from './LabApi';
import { LabApi } from './LabApi';
export * from './LabMaterialAssignmentApi';
import { LabMaterialAssignmentApi } from './LabMaterialAssignmentApi';
export * from './LabTestApprovalApi';
import { LabTestApprovalApi } from './LabTestApprovalApi';
export * from './LabTestDefaultApi';
import { LabTestDefaultApi } from './LabTestDefaultApi';
export * from './LineItemApi';
import { LineItemApi } from './LineItemApi';
export * from './MaterialApi';
import { MaterialApi } from './MaterialApi';
export * from './MaterialLineItemJoinApi';
import { MaterialLineItemJoinApi } from './MaterialLineItemJoinApi';
export * from './MaterialPayItemJoinApi';
import { MaterialPayItemJoinApi } from './MaterialPayItemJoinApi';
export * from './MaterialRecordOfMaterialEntryJoinApi';
import { MaterialRecordOfMaterialEntryJoinApi } from './MaterialRecordOfMaterialEntryJoinApi';
export * from './MixSpecificationApi';
import { MixSpecificationApi } from './MixSpecificationApi';
export * from './MixSpecificationMaterialJoinApi';
import { MixSpecificationMaterialJoinApi } from './MixSpecificationMaterialJoinApi';
export * from './ModuleApi';
import { ModuleApi } from './ModuleApi';
export * from './NotificationApi';
import { NotificationApi } from './NotificationApi';
export * from './ObservationApi';
import { ObservationApi } from './ObservationApi';
export * from './ObservationApprovalApi';
import { ObservationApprovalApi } from './ObservationApprovalApi';
export * from './ObservationCloneTemplatesApi';
import { ObservationCloneTemplatesApi } from './ObservationCloneTemplatesApi';
export * from './ObservationSearchsApi';
import { ObservationSearchsApi } from './ObservationSearchsApi';
export * from './ObservationSendToApi';
import { ObservationSendToApi } from './ObservationSendToApi';
export * from './ObservationsBatchTagApi';
import { ObservationsBatchTagApi } from './ObservationsBatchTagApi';
export * from './ObservationsByDocumentApi';
import { ObservationsByDocumentApi } from './ObservationsByDocumentApi';
export * from './ObservationsByUpdateDateApi';
import { ObservationsByUpdateDateApi } from './ObservationsByUpdateDateApi';
export * from './ObservationsFilterApi';
import { ObservationsFilterApi } from './ObservationsFilterApi';
export * from './OrganizationApi';
import { OrganizationApi } from './OrganizationApi';
export * from './OrganizationMaterialJoinApi';
import { OrganizationMaterialJoinApi } from './OrganizationMaterialJoinApi';
export * from './PayItemApi';
import { PayItemApi } from './PayItemApi';
export * from './ProductApi';
import { ProductApi } from './ProductApi';
export * from './ProductionPlantApi';
import { ProductionPlantApi } from './ProductionPlantApi';
export * from './ProductionPlantMaterialApprovalApi';
import { ProductionPlantMaterialApprovalApi } from './ProductionPlantMaterialApprovalApi';
export * from './ProjectApi';
import { ProjectApi } from './ProjectApi';
export * from './RecordOfMaterialApi';
import { RecordOfMaterialApi } from './RecordOfMaterialApi';
export * from './RecordOfMaterialEntryApi';
import { RecordOfMaterialEntryApi } from './RecordOfMaterialEntryApi';
export * from './RecordOfMaterialEntryArchiveApi';
import { RecordOfMaterialEntryArchiveApi } from './RecordOfMaterialEntryArchiveApi';
export * from './ReportApi';
import { ReportApi } from './ReportApi';
export * from './ReportNamedInstanceApi';
import { ReportNamedInstanceApi } from './ReportNamedInstanceApi';
export * from './SampleApi';
import { SampleApi } from './SampleApi';
export * from './SampleLabJoinApi';
import { SampleLabJoinApi } from './SampleLabJoinApi';
export * from './SampleLineItemJoinApi';
import { SampleLineItemJoinApi } from './SampleLineItemJoinApi';
export * from './SampleLogApi';
import { SampleLogApi } from './SampleLogApi';
export * from './TestApi';
import { TestApi } from './TestApi';
export * from './TestDataApi';
import { TestDataApi } from './TestDataApi';
export * from './TestInstanceApi';
import { TestInstanceApi } from './TestInstanceApi';
export * from './TestInstanceDataApi';
import { TestInstanceDataApi } from './TestInstanceDataApi';
export * from './TestInstanceDataArchiveApi';
import { TestInstanceDataArchiveApi } from './TestInstanceDataArchiveApi';
export * from './TestInstanceLabJoinApi';
import { TestInstanceLabJoinApi } from './TestInstanceLabJoinApi';
export * from './TestInstanceSampleJoinApi';
import { TestInstanceSampleJoinApi } from './TestInstanceSampleJoinApi';
export * from './TestLabJoinApi';
import { TestLabJoinApi } from './TestLabJoinApi';
export * from './TestPlanApi';
import { TestPlanApi } from './TestPlanApi';
export * from './TestRecordOfMaterialEntryJoinApi';
import { TestRecordOfMaterialEntryJoinApi } from './TestRecordOfMaterialEntryJoinApi';
export * from './TestSpecificationApi';
import { TestSpecificationApi } from './TestSpecificationApi';
export * from './TestSpecificationMaterialTestJoinApi';
import { TestSpecificationMaterialTestJoinApi } from './TestSpecificationMaterialTestJoinApi';
export * from './TestSpecificationRequirementApi';
import { TestSpecificationRequirementApi } from './TestSpecificationRequirementApi';
export * from './TestSpecificationSetApi';
import { TestSpecificationSetApi } from './TestSpecificationSetApi';
export * from './TestSpecificationSetTestJoinApi';
import { TestSpecificationSetTestJoinApi } from './TestSpecificationSetTestJoinApi';
export * from './TestStepApi';
import { TestStepApi } from './TestStepApi';
export * from './UserApi';
import { UserApi } from './UserApi';
export const APIS = [ArtifactApi, AuthenticateApi, BatchExportApi, BidItemApi, CommentApi, ContractApi, CustomerApi, DocumentApi, DocumentApprovalApi, DocumentSendToApi, DocumentsApi, DocumentsByObservationApi, ElectronicSignatureApi, EquipmentApi, LabApi, LabMaterialAssignmentApi, LabTestApprovalApi, LabTestDefaultApi, LineItemApi, MaterialApi, MaterialLineItemJoinApi, MaterialPayItemJoinApi, MaterialRecordOfMaterialEntryJoinApi, MixSpecificationApi, MixSpecificationMaterialJoinApi, ModuleApi, NotificationApi, ObservationApi, ObservationApprovalApi, ObservationCloneTemplatesApi, ObservationSearchsApi, ObservationSendToApi, ObservationsBatchTagApi, ObservationsByDocumentApi, ObservationsByUpdateDateApi, ObservationsFilterApi, OrganizationApi, OrganizationMaterialJoinApi, PayItemApi, ProductApi, ProductionPlantApi, ProductionPlantMaterialApprovalApi, ProjectApi, RecordOfMaterialApi, RecordOfMaterialEntryApi, RecordOfMaterialEntryArchiveApi, ReportApi, ReportNamedInstanceApi, SampleApi, SampleLabJoinApi, SampleLineItemJoinApi, SampleLogApi, TestApi, TestDataApi, TestInstanceApi, TestInstanceDataApi, TestInstanceDataArchiveApi, TestInstanceLabJoinApi, TestInstanceSampleJoinApi, TestLabJoinApi, TestPlanApi, TestRecordOfMaterialEntryJoinApi, TestSpecificationApi, TestSpecificationMaterialTestJoinApi, TestSpecificationRequirementApi, TestSpecificationSetApi, TestSpecificationSetTestJoinApi, TestStepApi, UserApi];
