/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface LineItem { 
    /**
     * 
     */
    IDLineItem: number;
    /**
     * 
     */
    GUIDLineItem: string;
    /**
     * 
     */
    CreateDate: Date;
    /**
     * 
     */
    CreatingIDUser: number;
    /**
     * 
     */
    UpdateDate: Date;
    /**
     * 
     */
    UpdatingIDUser: number;
    /**
     * 
     */
    Name: string;
    /**
     * 
     */
    Description: string;
    /**
     * 
     */
    Units: string;
    /**
     * 
     */
    CostPerUnit: string;
    /**
     * 
     */
    ExpectedQuantity: string;
    /**
     * 
     */
    ActualQuantity: string;
    /**
     * 
     */
    PercentComplete: number;
    /**
     * 
     */
    IDBidItem: number;
    /**
     * 
     */
    IDProject: number;
    /**
     * 
     */
    IDCustomer: number;
    /**
     * 
     */
    ExternalSyncDate: Date;
    /**
     * 
     */
    ContractQuantity: string;
    /**
     * 
     */
    InstalledQuantity: string;
    /**
     * 
     */
    Status: string;
    /**
     * 
     */
    ProposalIdentifier: string;
    /**
     * 
     */
    Notes: string;
    /**
     * 
     */
    SpecificationYear: number;
    /**
     * 
     */
    ItemCode: string;
    /**
     * 
     */
    ChangeOrderQuantity: string;
    /**
     * 
     */
    ChangeOrderQuantityPending: string;
    /**
     * 
     */
    ChangeOrderNumber: string;
    /**
     * 
     */
    FundingCategory: string;
    /**
     * 
     */
    CategoryNumber: string;
    /**
     * 
     */
    Tax: string;
}
