/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObservationFilterRequestDesignatedTime } from './observationFilterRequestDesignatedTime';
import { ObservationFilterRequestPriority } from './observationFilterRequestPriority';


/**
 * 
 */
export interface ObservationFilterRequest { 
    /**
     * 
     */
    SearchText: string;
    Priority: ObservationFilterRequestPriority;
    /**
     * 
     */
    ObservationType: Array<string>;
    /**
     * 
     */
    Contractors: Array<string>;
    DesignatedTime: ObservationFilterRequestDesignatedTime;
    /**
     * 
     */
    IDProject: number;
    DocumentCount: ObservationFilterRequestPriority;
    /**
     * 
     */
    IDArtifact: Array<number>;
}
