/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ObservationArchive { 
    /**
     * 
     */
    IDObservationArchive: number;
    /**
     * 
     */
    GUIDObservationArchive: string;
    /**
     * 
     */
    IDObservation: number;
    /**
     * 
     */
    GUIDObservation: string;
    /**
     * 
     */
    CreateDate: Date;
    /**
     * 
     */
    CreatingIDUser: number;
    /**
     * 
     */
    UpdateDate: Date;
    /**
     * 
     */
    UpdatingIDUser: number;
    /**
     * 
     */
    Deleted: number;
    /**
     * 
     */
    DeleteDate: Date;
    /**
     * 
     */
    DeletingIDUser: number;
    /**
     * 
     */
    Name: string;
    /**
     * 
     */
    Description: string;
    /**
     * 
     */
    IDDevice: number;
    /**
     * 
     */
    CaptureLatitude: string;
    /**
     * 
     */
    CaptureLongitude: string;
    /**
     * 
     */
    IDProject: number;
    /**
     * 
     */
    Priority: string;
    /**
     * 
     */
    Tags: string;
    /**
     * 
     */
    Contractors: string;
    /**
     * 
     */
    BidItems: string;
    /**
     * 
     */
    Version: number;
    /**
     * 
     */
    SpritePage: number;
    /**
     * 
     */
    DesignatedTime: Date;
    /**
     * 
     */
    ObservationType: string;
    /**
     * 
     */
    UserLatitude: string;
    /**
     * 
     */
    UserLongitude: string;
    /**
     * 
     */
    AlignmentStation: string;
    /**
     * 
     */
    AlignmentOffset: string;
    /**
     * 
     */
    SnapshotJSON: string;
    /**
     * 
     */
    AppHash: string;
    /**
     * 
     */
    Locked: number;
    /**
     * 
     */
    Transcoded: number;
    /**
     * 
     */
    Status: string;
    /**
     * 
     */
    StateName: string;
    /**
     * 
     */
    StateStep: number;
    /**
     * 
     */
    LineItems: string;
    /**
     * 
     */
    ExternalSyncDate: Date;
    /**
     * 
     */
    Equipment: string;
    /**
     * 
     */
    ExternalSyncGUID: string;
}
