/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ProjectModel { 
    /**
     * 
     */
    Tags: Array<string>;
    /**
     * 
     */
    BidItems: Array<string>;
    /**
     * 
     */
    LineItems: Array<string>;
    /**
     * 
     */
    Contractors: Array<string>;
    /**
     * 
     */
    TagTypes: Array<string>;
    /**
     * 
     */
    LabelTypes: any;
    /**
     * 
     */
    CustomProperties: any;
    /**
     * 
     */
    IDProject: number;
    /**
     * 
     */
    GUIDProject: string;
    /**
     * 
     */
    CreateDate: Date;
    /**
     * 
     */
    CreatingIDUser: number;
    /**
     * 
     */
    UpdateDate: Date;
    /**
     * 
     */
    UpdatingIDUser: number;
    /**
     * 
     */
    Name: string;
    /**
     * 
     */
    Description: string;
    /**
     * 
     */
    Deleted: number;
    /**
     * 
     */
    DeleteDate: Date;
    /**
     * 
     */
    DeletingIDUser: number;
    /**
     * 
     */
    Latitude: string;
    /**
     * 
     */
    Longitude: string;
    /**
     * 
     */
    IDCustomer: number;
    /**
     * 
     */
    IDContract: number;
    /**
     * 
     */
    ExternalSyncDate: Date;
    /**
     * 
     */
    Timezone: string;
    /**
     * 
     */
    Status: string;
}
