/**
 * HeadlightAPI
 * Pavia Headlight API Server
 *
 * OpenAPI spec version: 0.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface Sample { 
    /**
     * 
     */
    IDSample: number;
    /**
     * 
     */
    GUIDSample: string;
    /**
     * 
     */
    CreateDate: Date;
    /**
     * 
     */
    CreatingIDUser: number;
    /**
     * 
     */
    UpdateDate: Date;
    /**
     * 
     */
    UpdatingIDUser: number;
    /**
     * 
     */
    Deleted: number;
    /**
     * 
     */
    DeleteDate: Date;
    /**
     * 
     */
    DeletingIDUser: number;
    /**
     * 
     */
    ExternalSyncDate: Date;
    /**
     * 
     */
    IDCustomer: number;
    /**
     * 
     */
    QRCode: string;
    /**
     * 
     */
    CaptureLatitude: string;
    /**
     * 
     */
    CaptureLongitude: string;
    /**
     * 
     */
    Name: string;
    /**
     * 
     */
    IDProject: number;
    /**
     * 
     */
    ParentIDSample: number;
    /**
     * 
     */
    IDMaterial: number;
    /**
     * 
     */
    Notes: string;
    /**
     * 
     */
    IDProductionPlant: number;
    /**
     * 
     */
    IDLineItem: number;
    /**
     * 
     */
    RepresentedQuantityUnits: string;
    /**
     * 
     */
    SampledQuantityUnits: string;
    /**
     * 
     */
    LabControlNumber: string;
    /**
     * 
     */
    LabReferenceNumber: string;
    /**
     * 
     */
    ProductName: string;
    /**
     * 
     */
    MaterialType: string;
    /**
     * 
     */
    IDOrganization: number;
    /**
     * 
     */
    IDMixDesign: number;
    /**
     * 
     */
    ManufacturerCode: string;
    /**
     * 
     */
    IntendedUse: string;
    /**
     * 
     */
    BuyUSA: number;
    /**
     * 
     */
    ReceivedFrom: string;
    /**
     * 
     */
    GeographicalArea: string;
    /**
     * 
     */
    Station: string;
    /**
     * 
     */
    Offset: string;
    /**
     * 
     */
    RepresentedQuantity: string;
    /**
     * 
     */
    SampledQuantity: string;
    /**
     * 
     */
    Units: string;
    /**
     * 
     */
    RequestedBy: string;
    /**
     * 
     */
    Status: string;
    /**
     * 
     */
    ExternalSyncGUID: string;
    /**
     * 
     */
    IDLab: number;
    /**
     * 
     */
    IDProduct: number;
    /**
     * 
     */
    SampledByIDUser: number;
    /**
     * 
     */
    WitnessIDUser: number;
    /**
     * 
     */
    AuthorizedIDUser: number;
    /**
     * 
     */
    CMSIDUser: number;
    /**
     * 
     */
    Datum: string;
}
